### ISSUE TITLE
Usage examples bør inneholde både bygg og deploy

### ISSUE THREAD

**Issue by ahusby** [navikt/circleci-nais-orb#12]
Sitter og prøver å bruke denne orb-en. Ser på https://circleci.com/orbs/registry/orb/navikt/nais-deployment  under overskriften "Usage examples". Skulle ønske jeg kunne se eksempler på en "workflows" med "workflow" med "jobs" hvor bygg og deploy (med orb) ligger i hver sin jobb. I mine forsøk hittil har jeg ikke fått det til å funke.

Eksemplene viser enten deploy uten bygging (deploy-docker-and-nais og deploy-nais-only) eller bygging med `docker push`. Sistnevnte er ikke ønskelig, ref. https://github.com/navikt/circleci-nais-orb/issues/9 , for jeg trenger ikke `docker push` før jeg skal deploye.

**Comment by ahusby** [comment]
Dette feiler for meg med
```
Docker build00:12
Exit code: 1

#!/bin/sh -eo pipefail
docker build \
   \
  -f ./Dockerfile -t \
  docker.io/navikt/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 \
  .

Sending build context to Docker daemon  153.1kB

Step 1/2 : FROM navikt/java:11
11: Pulling from navikt/java
Digest: sha256:42bc85d6a244be62cc4a321959d706868394858085709312627e71b7f8085e49
Status: Downloaded newer image for navikt/java:11
 ---> 75d288915487
Step 2/2 : ADD "target/app-exec.jar" "/app/app.jar"

ADD failed: stat /var/lib/docker/tmp/docker-builder959112272/target/app-exec.jar: no such file or directory
Exited with code 1
```
```
version: 2.1
orbs:
  nais: navikt/nais-deployment@1.3.0
executors:
  my-executor:
    docker:
      - image: circleci/openjdk:11

jobs:
  build:
    executor: my-executor
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      # Download and cache Maven dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn package

workflows:
  version: 2
  my-workflow:
    jobs:
      - build
      - nais/deploy:
          name: "Build & push Docker image and deploy to cluster dev-fss"
          context: NAIS deployment
          repo: navikt/$CIRCLE_PROJECT_REPONAME
          image: navikt/$CIRCLE_PROJECT_REPONAME
          github-app-id: 30124
          nais-template: nais.yaml
          environment: dev-fss
          team: persondata
          requires:
            - build
```

**Comment by ahusby** [comment]
Her https://github.com/navikt/dp-vedtakresultat-lytter/blob/master/.circleci/config.yml har jeg funnet noen som omgår problemet ved å aldri bygge Docker image samtidig med deploy.

**Comment by ahusby** [comment]
Denne saken hører sammen med https://github.com/navikt/circleci-nais-orb/issues/5

**Comment by Kyrremann** [comment]
@ahusby i #18 har jeg delt opp docker build og docker push i to steg, holder det da med et eksempel som viser begge?
```
  build-push-docker:
    description: Build and push Docker image without creating NAIS deployment
    usage:
      version: 2.1
      orbs:
        nais: navikt/nais-deployment:XYZ
      jobs:
        build-and-push:
          docker:
            - image: circleci/openjdk:8-jdk
          steps:
            - checkout
            - run: some-custom-command?
            - nais/docker-build:
                image: navikt/example-image
            - nais/docker-push:
                image: navikt/example-image
      workflows:
        build-and-push-docker:
          jobs:
            - build-and-push
```
